# -*- coding: utf-8 -*-
from colorama import Fore

# =========================================================
# 💡 万能植物特征库：用于大厨房精准识别背包里的农作物、花卉与仙草
# =========================================================
PLANT_EMOJIS = [
    "🌾", "🍚", "🌽", "🥔", "🥕", "🍠", "🥬", "🥦", "🧅", "🧄", "🌱", "🍆", "🍅", "🥒", 
    "🎃", "🍈", "🌶", "🥜", "🌻", "🎋", "🍓", "🫐", "🍒", "🍎", "🍏", "🍌", "🍉", "🍇", 
    "🍊", "🍋", "🟩", "🍑", "🟣", "🥝", "🐉", "🟤", "𦔮", "🟡", "🌹", "🌷", "💮", "🌼", 
    "🔮", "🌿", "✨", "🔔", "🌸", "🌙", "🪴", "🌵", "🦋", "🔴", "☠", "🌺", "🪶", "🪵", 
    "🍄", "🐛", "❄", "🍃", "⚪", "🔥", "🍁", "🪺", "🍵", "𓏿", "🌳", "👁", "💀", "🥀", 
    "☯", "⭐", "☀️", "💧", "🌌", "⏳", "🌀", "⚙️", "⚡", "𫛛", "📦", "🪙", "💎", "👑"
]

# =========================================================
# 🧬 200种现实与赛博幻想植物大数据库
# =========================================================
PLANT_DATABASE = [
    # 基础与常见农作物
    {"id": 1, "name": "小麦", "cost": 10, "growth_time": 30, "yield_min": 2, "yield_max": 4, "value": 15, "exp": 5, "color": Fore.GREEN},
    {"id": 2, "name": "水稻", "cost": 12, "growth_time": 35, "yield_min": 2, "yield_max": 5, "value": 18, "exp": 6, "color": Fore.GREEN},
    {"id": 3, "name": "玉米", "cost": 15, "growth_time": 40, "yield_min": 3, "yield_max": 5, "value": 22, "exp": 8, "color": Fore.GREEN},
    {"id": 4, "name": "马铃薯", "cost": 10, "growth_time": 30, "yield_min": 2, "yield_max": 4, "value": 14, "exp": 4, "color": Fore.GREEN},
    {"id": 5, "name": "胡萝卜", "cost": 12, "growth_time": 35, "yield_min": 2, "yield_max": 4, "value": 16, "exp": 5, "color": Fore.GREEN},
    {"id": 6, "name": "白萝卜", "cost": 12, "growth_time": 35, "yield_min": 2, "yield_max": 4, "value": 16, "exp": 5, "color": Fore.GREEN},
    {"id": 7, "name": "红薯", "cost": 14, "growth_time": 38, "yield_min": 2, "yield_max": 5, "value": 20, "exp": 6, "color": Fore.GREEN},
    {"id": 8, "name": "大白菜", "cost": 8, "growth_time": 25, "yield_min": 1, "yield_max": 3, "value": 12, "exp": 3, "color": Fore.GREEN},
    {"id": 9, "name": "油菜", "cost": 8, "growth_time": 25, "yield_min": 1, "yield_max": 3, "value": 12, "exp": 3, "color": Fore.GREEN},
    {"id": 10, "name": "菠菜", "cost": 9, "growth_time": 28, "yield_min": 2, "yield_max": 4, "value": 13, "exp": 4, "color": Fore.GREEN},
    {"id": 11, "name": "西兰花", "cost": 18, "growth_time": 45, "yield_min": 2, "yield_max": 4, "value": 28, "exp": 9, "color": Fore.GREEN},
    {"id": 12, "name": "生菜", "cost": 10, "growth_time": 30, "yield_min": 2, "yield_max": 5, "value": 15, "exp": 5, "color": Fore.GREEN},
    {"id": 13, "name": "洋葱", "cost": 14, "growth_time": 36, "yield_min": 3, "yield_max": 5, "value": 21, "exp": 7, "color": Fore.GREEN},
    {"id": 14, "name": "大蒜", "cost": 16, "growth_time": 40, "yield_min": 4, "yield_max": 6, "value": 24, "exp": 8, "color": Fore.GREEN},
    {"id": 15, "name": "生姜", "cost": 16, "growth_time": 40, "yield_min": 2, "yield_max": 4, "value": 25, "exp": 8, "color": Fore.GREEN},
    {"id": 16, "name": "大葱", "cost": 10, "growth_time": 30, "yield_min": 2, "yield_max": 4, "value": 15, "exp": 5, "color": Fore.GREEN},
    {"id": 17, "name": "韭菜", "cost": 11, "growth_time": 32, "yield_min": 3, "yield_max": 5, "value": 17, "exp": 6, "color": Fore.GREEN},
    {"id": 18, "name": "茄子", "cost": 15, "growth_time": 42, "yield_min": 2, "yield_max": 4, "value": 23, "exp": 8, "color": Fore.GREEN},
    {"id": 19, "name": "番茄", "cost": 15, "growth_time": 40, "yield_min": 3, "yield_max": 5, "value": 22, "exp": 7, "color": Fore.GREEN},
    {"id": 20, "name": "黄瓜", "cost": 13, "growth_time": 35, "yield_min": 3, "yield_max": 5, "value": 20, "exp": 6, "color": Fore.GREEN},
    {"id": 21, "name": "南瓜", "cost": 25, "growth_time": 60, "yield_min": 1, "yield_max": 2, "value": 45, "exp": 15, "color": Fore.GREEN},
    {"id": 22, "name": "冬瓜", "cost": 22, "growth_time": 55, "yield_min": 1, "yield_max": 3, "value": 38, "exp": 13, "color": Fore.GREEN},
    {"id": 23, "name": "苦瓜", "cost": 14, "growth_time": 38, "yield_min": 2, "yield_max": 4, "value": 22, "exp": 7, "color": Fore.GREEN},
    {"id": 24, "name": "丝瓜", "cost": 13, "growth_time": 35, "yield_min": 3, "yield_max": 5, "value": 19, "exp": 6, "color": Fore.GREEN},
    {"id": 25, "name": "辣椒", "cost": 15, "growth_time": 38, "yield_min": 4, "yield_max": 8, "value": 24, "exp": 8, "color": Fore.GREEN},
    {"id": 26, "name": "青椒", "cost": 14, "growth_time": 36, "yield_min": 3, "yield_max": 5, "value": 21, "exp": 7, "color": Fore.GREEN},
    {"id": 27, "name": "花椰菜", "cost": 18, "growth_time": 45, "yield_min": 2, "yield_max": 4, "value": 27, "exp": 9, "color": Fore.GREEN},
    {"id": 28, "name": "四季豆", "cost": 12, "growth_time": 34, "yield_min": 4, "yield_max": 7, "value": 19, "exp": 6, "color": Fore.GREEN},
    {"id": 29, "name": "豌豆", "cost": 14, "growth_time": 38, "yield_min": 4, "yield_max": 7, "value": 22, "exp": 7, "color": Fore.GREEN},
    {"id": 30, "name": "毛豆", "cost": 12, "growth_time": 35, "yield_min": 4, "yield_max": 6, "value": 18, "exp": 6, "color": Fore.GREEN},
    {"id": 31, "name": "花生", "cost": 16, "growth_time": 45, "yield_min": 5, "yield_max": 10, "value": 26, "exp": 9, "color": Fore.GREEN},
    {"id": 32, "name": "向日葵", "cost": 20, "growth_time": 50, "yield_min": 3, "yield_max": 6, "value": 35, "exp": 11, "color": Fore.GREEN},
    {"id": 33, "name": "芝麻", "cost": 15, "growth_time": 42, "yield_min": 4, "yield_max": 8, "value": 25, "exp": 8, "color": Fore.GREEN},
    {"id": 34, "name": "甘蔗", "cost": 24, "growth_time": 65, "yield_min": 2, "yield_max": 5, "value": 42, "exp": 14, "color": Fore.GREEN},
    {"id": 35, "name": "甜菜", "cost": 16, "growth_time": 40, "yield_min": 2, "yield_max": 4, "value": 26, "exp": 8, "color": Fore.GREEN},
    {"id": 36, "name": "木薯", "cost": 18, "growth_time": 45, "yield_min": 3, "yield_max": 5, "value": 30, "exp": 10, "color": Fore.GREEN},
    {"id": 37, "name": "高粱", "cost": 15, "growth_time": 40, "yield_min": 3, "yield_max": 5, "value": 24, "exp": 8, "color": Fore.GREEN},
    {"id": 38, "name": "燕麦", "cost": 14, "growth_time": 38, "yield_min": 3, "yield_max": 5, "value": 22, "exp": 7, "color": Fore.GREEN},
    {"id": 39, "name": "大麦", "cost": 14, "growth_time": 38, "yield_min": 3, "yield_max": 5, "value": 22, "exp": 7, "color": Fore.GREEN},
    {"id": 40, "name": "荞麦", "cost": 13, "growth_time": 36, "yield_min": 3, "yield_max": 5, "value": 20, "exp": 7, "color": Fore.GREEN},

    # 缤纷高能水果类
    {"id": 41, "name": "草莓", "cost": 30, "growth_time": 50, "yield_min": 4, "yield_max": 8, "value": 55, "exp": 15, "color": Fore.YELLOW},
    {"id": 42, "name": "蓝莓", "cost": 35, "growth_time": 55, "yield_min": 6, "yield_max": 12, "value": 65, "exp": 18, "color": Fore.YELLOW},
    {"id": 43, "name": "黑莓", "cost": 38, "growth_time": 58, "yield_min": 5, "yield_max": 10, "value": 70, "exp": 20, "color": Fore.YELLOW},
    {"id": 44, "name": "红树莓", "cost": 40, "growth_time": 60, "yield_min": 5, "yield_max": 10, "value": 75, "exp": 22, "color": Fore.YELLOW},
    {"id": 45, "name": "车厘子", "cost": 60, "growth_time": 90, "yield_min": 3, "yield_max": 6, "value": 120, "exp": 35, "color": Fore.YELLOW},
    {"id": 46, "name": "红苹果", "cost": 20, "growth_time": 45, "yield_min": 3, "yield_max": 6, "value": 38, "exp": 10, "color": Fore.YELLOW},
    {"id": 47, "name": "青苹果", "cost": 20, "growth_time": 45, "yield_min": 3, "yield_max": 6, "value": 38, "exp": 10, "color": Fore.YELLOW},
    {"id": 48, "name": "香蕉", "cost": 22, "growth_time": 48, "yield_min": 4, "yield_max": 8, "value": 42, "exp": 12, "color": Fore.YELLOW},
    {"id": 49, "name": "西瓜", "cost": 40, "growth_time": 75, "yield_min": 1, "yield_max": 2, "value": 85, "exp": 25, "color": Fore.YELLOW},
    {"id": 50, "name": "巨峰葡萄", "cost": 32, "growth_time": 55, "yield_min": 3, "yield_max": 6, "value": 60, "exp": 16, "color": Fore.YELLOW},
    {"id": 51, "name": "水晶葡萄", "cost": 32, "growth_time": 55, "yield_min": 3, "yield_max": 6, "value": 60, "exp": 16, "color": Fore.YELLOW},
    {"id": 52, "name": "哈密瓜", "cost": 45, "growth_time": 80, "yield_min": 1, "yield_max": 3, "value": 95, "exp": 28, "color": Fore.YELLOW},
    {"id": 53, "name": "香瓜", "cost": 25, "growth_time": 50, "yield_min": 2, "yield_max": 4, "value": 48, "exp": 14, "color": Fore.YELLOW},
    {"id": 54, "name": "甜橙", "cost": 24, "growth_time": 50, "yield_min": 3, "yield_max": 6, "value": 46, "exp": 13, "color": Fore.YELLOW},
    {"id": 55, "name": "柠檬", "cost": 20, "growth_time": 45, "yield_min": 3, "yield_max": 6, "value": 40, "exp": 11, "color": Fore.YELLOW},
    {"id": 56, "name": "青柠", "cost": 22, "growth_time": 46, "yield_min": 3, "yield_max": 6, "value": 43, "exp": 12, "color": Fore.YELLOW},
    {"id": 57, "name": "红西柚", "cost": 28, "growth_time": 55, "yield_min": 2, "yield_max": 5, "value": 56, "exp": 16, "color": Fore.YELLOW},
    {"id": 58, "name": "金桔", "cost": 18, "growth_time": 40, "yield_min": 5, "yield_max": 10, "value": 35, "exp": 10, "color": Fore.YELLOW},
    {"id": 59, "name": "砂糖橘", "cost": 20, "growth_time": 42, "yield_min": 6, "yield_max": 12, "value": 40, "exp": 11, "color": Fore.YELLOW},
    {"id": 60, "name": "白桃", "cost": 30, "growth_time": 60, "yield_min": 2, "yield_max": 5, "value": 62, "exp": 18, "color": Fore.YELLOW},
    {"id": 61, "name": "油桃", "cost": 28, "growth_time": 58, "yield_min": 2, "yield_max": 5, "value": 58, "exp": 17, "color": Fore.YELLOW},
    {"id": 62, "name": "蟠桃", "cost": 45, "growth_time": 75, "yield_min": 2, "yield_max": 4, "value": 90, "exp": 25, "color": Fore.YELLOW},
    {"id": 63, "name": "黄桃", "cost": 32, "growth_time": 60, "yield_min": 2, "yield_max": 5, "value": 65, "exp": 19, "color": Fore.YELLOW},
    {"id": 64, "name": "红富士", "cost": 25, "growth_time": 50, "yield_min": 3, "yield_max": 6, "value": 50, "exp": 14, "color": Fore.YELLOW},
    {"id": 65, "name": "乌梅", "cost": 35, "growth_time": 65, "yield_min": 4, "yield_max": 8, "value": 75, "exp": 21, "color": Fore.YELLOW},
    {"id": 66, "name": "杨梅", "cost": 38, "growth_time": 68, "yield_min": 4, "yield_max": 8, "value": 80, "exp": 23, "color": Fore.YELLOW},
    {"id": 67, "name": "桑葚", "cost": 30, "growth_time": 55, "yield_min": 5, "yield_max": 10, "value": 65, "exp": 17, "color": Fore.YELLOW},
    {"id": 68, "name": "无花果", "cost": 40, "growth_time": 70, "yield_min": 2, "yield_max": 5, "value": 85, "exp": 24, "color": Fore.YELLOW},
    {"id": 69, "name": "百香果", "cost": 36, "growth_time": 60, "yield_min": 3, "yield_max": 7, "value": 76, "exp": 20, "color": Fore.YELLOW},
    {"id": 70, "name": "奇异果", "cost": 42, "growth_time": 72, "yield_min": 3, "yield_max": 6, "value": 90, "exp": 26, "color": Fore.YELLOW},
    {"id": 71, "name": "火龙果", "cost": 44, "growth_time": 75, "yield_min": 2, "yield_max": 4, "value": 92, "exp": 27, "color": Fore.YELLOW},
    {"id": 72, "name": "红毛丹", "cost": 48, "growth_time": 78, "yield_min": 4, "yield_max": 8, "value": 105, "exp": 30, "color": Fore.YELLOW},
    {"id": 73, "name": "山竹", "cost": 55, "growth_time": 85, "yield_min": 3, "yield_max": 6, "value": 125, "exp": 36, "color": Fore.YELLOW},
    {"id": 74, "name": "榴莲", "cost": 100, "growth_time": 120, "yield_min": 1, "yield_max": 2, "value": 260, "exp": 65, "color": Fore.YELLOW},
    {"id": 75, "name": "菠萝蜜", "cost": 85, "growth_time": 110, "yield_min": 1, "yield_max": 2, "value": 210, "exp": 55, "color": Fore.YELLOW},
    {"id": 76, "name": "木瓜", "cost": 34, "growth_time": 60, "yield_min": 2, "yield_max": 4, "value": 72, "exp": 20, "color": Fore.YELLOW},
    {"id": 77, "name": "荔枝", "cost": 50, "growth_time": 80, "yield_min": 4, "yield_max": 8, "value": 115, "exp": 32, "color": Fore.YELLOW},
    {"id": 78, "name": "龙眼", "cost": 45, "growth_time": 75, "yield_min": 5, "yield_max": 9, "value": 100, "exp": 29, "color": Fore.YELLOW},
    {"id": 79, "name": "批把", "cost": 40, "growth_time": 70, "yield_min": 3, "yield_max": 6, "value": 88, "exp": 25, "color": Fore.YELLOW},
    {"id": 80, "name": "大红枣", "cost": 25, "growth_time": 50, "yield_min": 5, "yield_max": 10, "value": 55, "exp": 15, "color": Fore.YELLOW},

    # 园艺观赏花卉草木类
    {"id": 81, "name": "红玫瑰", "cost": 50, "growth_time": 60, "yield_min": 2, "yield_max": 4, "value": 110, "exp": 30, "color": Fore.LIGHTRED_EX},
    {"id": 82, "name": "白玫瑰", "cost": 50, "growth_time": 60, "yield_min": 2, "yield_max": 4, "value": 110, "exp": 30, "color": Fore.LIGHTWHITE_EX},
    {"id": 83, "name": "蓝色妖姬", "cost": 80, "growth_time": 80, "yield_min": 2, "yield_max": 4, "value": 190, "exp": 45, "color": Fore.LIGHTBLUE_EX},
    {"id": 84, "name": "黄郁金香", "cost": 55, "growth_time": 65, "yield_min": 2, "yield_max": 5, "value": 125, "exp": 33, "color": Fore.LIGHTYELLOW_EX},
    {"id": 85, "name": "粉郁金香", "cost": 55, "growth_time": 65, "yield_min": 2, "yield_max": 5, "value": 125, "exp": 33, "color": Fore.LIGHTMAGENTA_EX},
    {"id": 86, "name": "康乃馨", "cost": 40, "growth_time": 55, "yield_min": 3, "yield_max": 6, "value": 90, "exp": 25, "color": Fore.LIGHTRED_EX},
    {"id": 87, "name": "向日葵花", "cost": 30, "growth_time": 50, "yield_min": 2, "yield_max": 5, "value": 70, "exp": 18, "color": Fore.LIGHTYELLOW_EX},
    {"id": 88, "name": "雏菊", "cost": 25, "growth_time": 40, "yield_min": 4, "yield_max": 8, "value": 58, "exp": 15, "color": Fore.LIGHTWHITE_EX},
    {"id": 89, "name": "蒲公英", "cost": 15, "growth_time": 30, "yield_min": 3, "yield_max": 6, "value": 35, "exp": 10, "color": Fore.LIGHTGREEN_EX},
    {"id": 90, "name": "薰衣草", "cost": 45, "growth_time": 60, "yield_min": 3, "yield_max": 6, "value": 105, "exp": 28, "color": Fore.MAGENTA},
    {"id": 91, "name": "迷迭香", "cost": 35, "growth_time": 50, "yield_min": 3, "yield_max": 5, "value": 80, "exp": 22, "color": Fore.LIGHTGREEN_EX},
    {"id": 92, "name": "薄荷草", "cost": 20, "growth_time": 35, "yield_min": 4, "yield_max": 8, "value": 45, "exp": 12, "color": Fore.LIGHTGREEN_EX},
    {"id": 93, "name": "九层塔", "cost": 25, "growth_time": 38, "yield_min": 3, "yield_max": 6, "value": 56, "exp": 14, "color": Fore.LIGHTGREEN_EX},
    {"id": 94, "name": "勿忘我", "cost": 48, "growth_time": 62, "yield_min": 2, "yield_max": 5, "value": 112, "exp": 29, "color": Fore.LIGHTBLUE_EX},
    {"id": 95, "name": "满天星", "cost": 35, "growth_time": 45, "yield_min": 5, "yield_max": 10, "value": 85, "exp": 22, "color": Fore.LIGHTWHITE_EX},
    {"id": 96, "name": "风铃草", "cost": 42, "growth_time": 58, "yield_min": 3, "yield_max": 6, "value": 96, "exp": 26, "color": Fore.LIGHTBLUE_EX},
    {"id": 97, "name": "波斯宿", "cost": 30, "growth_time": 45, "yield_min": 4, "yield_max": 7, "value": 70, "exp": 19, "color": Fore.LIGHTMAGENTA_EX},
    {"id": 98, "name": "紫罗兰", "cost": 50, "growth_time": 65, "yield_min": 2, "yield_max": 5, "value": 120, "exp": 31, "color": Fore.MAGENTA},
    {"id": 99, "name": "茉莉花", "cost": 45, "growth_time": 55, "yield_min": 3, "yield_max": 6, "value": 105, "exp": 27, "color": Fore.LIGHTWHITE_EX},
    {"id": 100, "name": "栀子花", "cost": 45, "growth_time": 55, "yield_min": 2, "yield_max": 5, "value": 105, "exp": 27, "color": Fore.LIGHTWHITE_EX},
    {"id": 101, "name": "夜来香", "cost": 55, "growth_time": 70, "yield_min": 2, "yield_max": 4, "value": 135, "exp": 34, "color": Fore.LIGHTYELLOW_EX},
    {"id": 102, "name": "含羞草", "cost": 25, "growth_time": 40, "yield_min": 2, "yield_max": 4, "value": 55, "exp": 15, "color": Fore.LIGHTGREEN_EX},
    {"id": 103, "name": "猪笼草", "cost": 65, "growth_time": 85, "yield_min": 1, "yield_max": 3, "value": 160, "exp": 40, "color": Fore.LIGHTGREEN_EX},
    {"id": 104, "name": "捕蝇草", "cost": 70, "growth_time": 90, "yield_min": 1, "yield_max": 3, "value": 175, "exp": 45, "color": Fore.LIGHTGREEN_EX},
    {"id": 105, "name": "长寿花", "cost": 38, "growth_time": 50, "yield_min": 3, "yield_max": 6, "value": 88, "exp": 23, "color": Fore.LIGHTRED_EX},
    {"id": 106, "name": "仙人掌", "cost": 20, "growth_time": 45, "yield_min": 2, "yield_max": 5, "value": 45, "exp": 12, "color": Fore.GREEN},
    {"id": 107, "name": "芦荟", "cost": 25, "growth_time": 42, "yield_min": 2, "yield_max": 4, "value": 58, "exp": 16, "color": Fore.LIGHTGREEN_EX},
    {"id": 108, "name": "多肉玉露", "cost": 40, "growth_time": 55, "yield_min": 2, "yield_max": 4, "value": 95, "exp": 24, "color": Fore.LIGHTGREEN_EX},
    {"id": 109, "name": "观音莲", "cost": 35, "growth_time": 50, "yield_min": 2, "yield_max": 5, "value": 82, "exp": 21, "color": Fore.LIGHTGREEN_EX},
    {"id": 110, "name": "常春藤", "cost": 30, "growth_time": 45, "yield_min": 3, "yield_max": 6, "value": 68, "exp": 18, "color": Fore.LIGHTGREEN_EX},
    {"id": 111, "name": "绿萝", "cost": 15, "growth_time": 30, "yield_min": 4, "yield_max": 8, "value": 35, "exp": 9, "color": Fore.LIGHTGREEN_EX},
    {"id": 112, "name": "富贵竹", "cost": 50, "growth_time": 70, "yield_min": 2, "yield_max": 4, "value": 120, "exp": 32, "color": Fore.GREEN},
    {"id": 113, "name": "文竹", "cost": 45, "growth_time": 65, "yield_min": 2, "yield_max": 4, "value": 108, "exp": 28, "color": Fore.LIGHTGREEN_EX},
    {"id": 114, "name": "君子兰", "cost": 90, "growth_time": 100, "yield_min": 1, "yield_max": 3, "value": 230, "exp": 60, "color": Fore.LIGHTGREEN_EX},
    {"id": 115, "name": "蝴蝶兰", "cost": 110, "growth_time": 110, "yield_min": 1, "yield_max": 3, "value": 280, "exp": 70, "color": Fore.LIGHTMAGENTA_EX},
    {"id": 116, "name": "彼岸花", "cost": 130, "growth_time": 120, "yield_min": 1, "yield_max": 3, "value": 340, "exp": 85, "color": Fore.RED},
    {"id": 117, "name": "曼陀罗花", "cost": 140, "growth_time": 125, "yield_min": 1, "yield_max": 3, "value": 370, "exp": 90, "color": Fore.MAGENTA},
    {"id": 118, "name": "虞美人", "cost": 60, "growth_time": 70, "yield_min": 3, "yield_max": 6, "value": 145, "exp": 38, "color": Fore.LIGHTRED_EX},
    {"id": 119, "name": "鸡冠花", "cost": 40, "growth_time": 55, "yield_min": 3, "yield_max": 6, "value": 92, "exp": 24, "color": Fore.LIGHTRED_EX},
    {"id": 120, "name": "夹竹桃", "cost": 75, "growth_time": 80, "yield_min": 2, "yield_max": 4, "value": 180, "exp": 48, "color": Fore.LIGHTMAGENTA_EX},

    # 传世名贵中华中药材类
    {"id": 121, "name": "长白山人参", "cost": 300, "growth_time": 200, "yield_min": 1, "yield_max": 2, "value": 950, "exp": 200, "color": Fore.YELLOW},
    {"id": 122, "name": "林下参", "cost": 200, "growth_time": 160, "yield_min": 1, "yield_max": 2, "value": 600, "exp": 130, "color": Fore.YELLOW},
    {"id": 123, "name": "西洋参", "cost": 180, "growth_time": 150, "yield_min": 1, "yield_max": 2, "value": 520, "exp": 110, "color": Fore.YELLOW},
    {"id": 124, "name": "野生灵芝", "cost": 350, "growth_time": 220, "yield_min": 1, "yield_max": 1, "value": 1200, "exp": 250, "color": Fore.MAGENTA},
    {"id": 125, "name": "赤灵芝", "cost": 250, "growth_time": 180, "yield_min": 1, "yield_max": 2, "value": 800, "exp": 170, "color": Fore.MAGENTA},
    {"id": 126, "name": "冬虫假草", "cost": 400, "growth_time": 250, "yield_min": 1, "yield_max": 3, "value": 1500, "exp": 300, "color": Fore.LIGHTYELLOW_EX},
    {"id": 127, "name": "藏红花", "cost": 150, "growth_time": 120, "yield_min": 3, "yield_max": 6, "value": 450, "exp": 95, "color": Fore.LIGHTRED_EX},
    {"id": 128, "name": "天山雪莲", "cost": 500, "growth_time": 300, "yield_min": 1, "yield_max": 1, "value": 2200, "exp": 450, "color": Fore.LIGHTWHITE_EX},
    {"id": 129, "name": "鹿茸草", "cost": 90, "growth_time": 85, "yield_min": 2, "yield_max": 4, "value": 240, "exp": 55, "color": Fore.LIGHTGREEN_EX},
    {"id": 130, "name": "铁皮石斛", "cost": 220, "growth_time": 170, "yield_min": 2, "yield_max": 4, "value": 730, "exp": 150, "color": Fore.LIGHTGREEN_EX},
    {"id": 131, "name": "何首乌", "cost": 130, "growth_time": 110, "yield_min": 1, "yield_max": 3, "value": 390, "exp": 80, "color": Fore.YELLOW},
    {"id": 132, "name": "当归", "cost": 70, "growth_time": 75, "yield_min": 2, "yield_max": 5, "value": 195, "exp": 45, "color": Fore.LIGHTGREEN_EX},
    {"id": 133, "name": "黄芪", "cost": 65, "growth_time": 70, "yield_min": 2, "yield_max": 5, "value": 180, "exp": 40, "color": Fore.LIGHTGREEN_EX},
    {"id": 134, "name": "枸杞子", "cost": 45, "growth_time": 60, "yield_min": 5, "yield_max": 12, "value": 135, "exp": 30, "color": Fore.LIGHTRED_EX},
    {"id": 135, "name": "绞股蓝", "cost": 50, "growth_time": 62, "yield_min": 3, "yield_max": 6, "value": 140, "exp": 32, "color": Fore.LIGHTGREEN_EX},
    {"id": 136, "name": "三七", "cost": 110, "growth_time": 100, "yield_min": 1, "yield_max": 3, "value": 320, "exp": 70, "color": Fore.YELLOW},
    {"id": 137, "name": "金银花", "cost": 40, "growth_time": 50, "yield_min": 4, "yield_max": 8, "value": 110, "exp": 25, "color": Fore.LIGHTWHITE_EX},
    {"id": 138, "name": "板蓝根", "cost": 30, "growth_time": 45, "yield_min": 2, "yield_max": 5, "value": 85, "exp": 20, "color": Fore.YELLOW},
    {"id": 139, "name": "连翘", "cost": 35, "growth_time": 48, "yield_min": 3, "yield_max": 6, "value": 98, "exp": 22, "color": Fore.LIGHTYELLOW_EX},
    {"id": 140, "name": "柴胡", "cost": 45, "growth_time": 55, "yield_min": 2, "yield_max": 5, "value": 125, "exp": 28, "color": Fore.LIGHTGREEN_EX},
    {"id": 141, "name": "薄荷叶", "cost": 15, "growth_time": 30, "yield_min": 5, "yield_max": 10, "value": 42, "exp": 10, "color": Fore.LIGHTGREEN_EX},
    {"id": 142, "name": "甘草", "cost": 25, "growth_time": 40, "yield_min": 2, "yield_max": 5, "value": 72, "exp": 16, "color": Fore.YELLOW},
    {"id": 143, "name": "罗汉果", "cost": 60, "growth_time": 75, "yield_min": 2, "yield_max": 5, "value": 170, "exp": 38, "color": Fore.YELLOW},
    {"id": 144, "name": "胖大海", "cost": 55, "growth_time": 70, "yield_min": 3, "yield_max": 6, "value": 155, "exp": 35, "color": Fore.YELLOW},
    {"id": 145, "name": "陈皮梅", "cost": 40, "growth_time": 55, "yield_min": 4, "yield_max": 8, "value": 112, "exp": 26, "color": Fore.LIGHTYELLOW_EX},
    {"id": 146, "name": "西洋参片", "cost": 100, "growth_time": 90, "yield_min": 3, "yield_max": 6, "value": 280, "exp": 60, "color": Fore.YELLOW},
    {"id": 147, "name": "天麻", "cost": 120, "growth_time": 105, "yield_min": 1, "yield_max": 3, "value": 345, "exp": 75, "color": Fore.YELLOW},
    {"id": 148, "name": "茯苓", "cost": 75, "growth_time": 80, "yield_min": 2, "yield_max": 4, "value": 210, "exp": 48, "color": Fore.YELLOW},
    {"id": 149, "name": "白术", "cost": 70, "growth_time": 78, "yield_min": 2, "yield_max": 5, "value": 198, "exp": 44, "color": Fore.LIGHTGREEN_EX},
    {"id": 150, "name": "川贝", "cost": 160, "growth_time": 130, "yield_min": 4, "yield_max": 8, "value": 460, "exp": 100, "color": Fore.LIGHTWHITE_EX},
    {"id": 151, "name": "批把叶", "cost": 20, "growth_time": 35, "yield_min": 4, "yield_max": 8, "value": 54, "exp": 13, "color": Fore.LIGHTGREEN_EX},
    {"id": 152, "name": "麦冬", "cost": 38, "growth_time": 50, "yield_min": 3, "yield_max": 6, "value": 105, "exp": 24, "color": Fore.LIGHTGREEN_EX},
    {"id": 153, "name": "沙棘果", "cost": 50, "growth_time": 65, "yield_min": 5, "yield_max": 12, "value": 148, "exp": 33, "color": Fore.LIGHTYELLOW_EX},
    {"id": 154, "name": "黑枸杞", "cost": 75, "growth_time": 80, "yield_min": 4, "yield_max": 10, "value": 220, "exp": 48, "color": Fore.MAGENTA},
    {"id": 155, "name": "决明子", "cost": 25, "growth_time": 40, "yield_min": 4, "yield_max": 8, "value": 72, "exp": 16, "color": Fore.YELLOW},
    {"id": 156, "name": "酸枣仁", "cost": 80, "growth_time": 85, "yield_min": 3, "yield_max": 6, "value": 235, "exp": 52, "color": Fore.YELLOW},
    {"id": 157, "name": "益智仁", "cost": 70, "growth_time": 80, "yield_min": 3, "yield_max": 6, "value": 205, "exp": 46, "color": Fore.YELLOW},
    {"id": 158, "name": "远志", "cost": 65, "growth_time": 75, "yield_min": 2, "yield_max": 5, "value": 185, "exp": 42, "color": Fore.LIGHTGREEN_EX},
    {"id": 159, "name": "合欢皮", "cost": 50, "growth_time": 65, "yield_min": 2, "yield_max": 4, "value": 142, "exp": 32, "color": Fore.YELLOW},
    {"id": 160, "name": "断肠草", "cost": 150, "growth_time": 100, "yield_min": 1, "yield_max": 3, "value": 480, "exp": 99, "color": Fore.RED},

    # 梦幻神话、史诗与高概念赛博仙草类
    {"id": 161, "name": "冰晶雪莲", "cost": 800, "growth_time": 400, "yield_min": 1, "yield_max": 1, "value": 4500, "exp": 800, "color": Fore.LIGHTWHITE_EX},
    {"id": 162, "name": "烈焰火莲", "cost": 800, "growth_time": 400, "yield_min": 1, "yield_max": 1, "value": 4500, "exp": 800, "color": Fore.RED},
    {"id": 163, "name": "九叶重楼", "cost": 600, "growth_time": 320, "yield_min": 1, "yield_max": 2, "value": 3200, "exp": 600, "color": Fore.LIGHTRED_EX},
    {"id": 164, "name": "七叶一枝花", "cost": 550, "growth_time": 300, "yield_min": 1, "yield_max": 2, "value": 2900, "exp": 550, "color": Fore.LIGHTMAGENTA_EX},
    {"id": 165, "name": "不死神草", "cost": 1500, "growth_time": 600, "yield_min": 1, "yield_max": 1, "value": 9999, "exp": 1500, "color": Fore.LIGHTYELLOW_EX},
    {"id": 166, "name": "还魂草", "cost": 900, "growth_time": 450, "yield_min": 1, "yield_max": 1, "value": 5500, "exp": 900, "color": Fore.LIGHTGREEN_EX},
    {"id": 167, "name": "洗髓芝", "cost": 1000, "growth_time": 500, "yield_min": 1, "yield_max": 1, "value": 6600, "exp": 1000, "color": Fore.MAGENTA},
    {"id": 168, "name": "龙血果", "cost": 1200, "growth_time": 550, "yield_min": 1, "yield_max": 2, "value": 7800, "exp": 1200, "color": Fore.RED},
    {"id": 169, "name": "凤血巢", "cost": 1300, "growth_time": 580, "yield_min": 1, "yield_max": 1, "value": 8500, "exp": 1300, "color": Fore.LIGHTRED_EX},
    {"id": 170, "name": "悟道茶树", "cost": 2000, "growth_time": 800, "yield_min": 2, "yield_max": 5, "value": 15000, "exp": 2500, "color": Fore.GREEN},
    {"id": 171, "name": "菩提子", "cost": 1800, "growth_time": 750, "yield_min": 3, "yield_max": 6, "value": 13500, "exp": 2200, "color": Fore.YELLOW},
    {"id": 172, "name": "生命之树幼苗", "cost": 3000, "growth_time": 1200, "yield_min": 1, "yield_max": 1, "value": 35000, "exp": 5000, "color": Fore.LIGHTGREEN_EX},
    {"id": 173, "name": "精灵果", "cost": 700, "growth_time": 350, "yield_min": 2, "yield_max": 4, "value": 3900, "exp": 700, "color": Fore.LIGHTGREEN_EX},
    {"id": 174, "name": "恶魔之眼", "cost": 950, "growth_time": 480, "yield_min": 1, "yield_max": 2, "value": 5900, "exp": 950, "color": Fore.RED},
    {"id": 175, "name": "荧光蕈", "cost": 400, "growth_time": 240, "yield_min": 4, "yield_max": 8, "value": 2100, "exp": 400, "color": Fore.LIGHTBLUE_EX},
    {"id": 176, "name": "幽冥鬼兰", "cost": 1600, "growth_time": 700, "yield_min": 1, "yield_max": 1, "value": 12500, "exp": 1800, "color": Fore.LIGHTWHITE_EX},
    {"id": 177, "name": "嗜血藤", "cost": 850, "growth_time": 420, "yield_min": 2, "yield_max": 5, "value": 4800, "exp": 850, "color": Fore.RED},
    {"id": 178, "name": "曼陀罗妖花", "cost": 1100, "growth_time": 520, "yield_min": 1, "yield_max": 2, "value": 7200, "exp": 1100, "color": Fore.MAGENTA},
    {"id": 179, "name": "噬魂草", "cost": 1050, "growth_time": 500, "yield_min": 2, "yield_max": 4, "value": 6900, "exp": 1050, "color": Fore.MAGENTA},
    {"id": 180, "name": "冰火两重草", "cost": 1400, "growth_time": 650, "yield_min": 1, "yield_max": 2, "value": 9200, "exp": 1400, "color": Fore.CYAN},
    {"id": 181, "name": "星光草", "cost": 500, "growth_time": 260, "yield_min": 3, "yield_max": 6, "value": 2600, "exp": 500, "color": Fore.LIGHTBLUE_EX},
    {"id": 182, "name": "月华草", "cost": 550, "growth_time": 280, "yield_min": 3, "yield_max": 6, "value": 2900, "exp": 550, "color": Fore.LIGHTWHITE_EX},
    {"id": 183, "name": "烈阳花", "cost": 600, "growth_time": 300, "yield_min": 2, "yield_max": 5, "value": 3300, "exp": 600, "color": Fore.LIGHTYELLOW_EX},
    {"id": 184, "name": "晨曦露珠花", "cost": 450, "growth_time": 230, "yield_min": 3, "yield_max": 6, "value": 2300, "exp": 450, "color": Fore.CYAN},
    {"id": 185, "name": "暮色菇", "cost": 480, "growth_time": 250, "yield_min": 4, "yield_max": 8, "value": 2500, "exp": 480, "color": Fore.MAGENTA},
    {"id": 186, "name": "虚空藤蔓", "cost": 2200, "growth_time": 900, "yield_min": 1, "yield_max": 3, "value": 18000, "exp": 2500, "color": Fore.MAGENTA},
    {"id": 187, "name": "时之砂晶花", "cost": 2500, "growth_time": 1000, "yield_min": 1, "yield_max": 2, "value": 22000, "exp": 3000, "color": Fore.LIGHTYELLOW_EX},
    {"id": 188, "name": "空间跃迁果", "cost": 2600, "growth_time": 1050, "yield_min": 1, "yield_max": 2, "value": 24000, "exp": 3200, "color": Fore.CYAN},
    {"id": 189, "name": "量子纠缠玫瑰", "cost": 2800, "growth_time": 1100, "yield_min": 2, "yield_max": 2, "value": 27000, "exp": 3500, "color": Fore.LIGHTRED_EX},
    {"id": 190, "name": "反物质仙人掌", "cost": 2400, "growth_time": 950, "yield_min": 1, "yield_max": 3, "value": 21000, "exp": 2800, "color": Fore.GREEN},
    {"id": 191, "name": "暗物质苔藓", "cost": 2300, "growth_time": 920, "yield_min": 5, "yield_max": 10, "value": 20000, "exp": 2700, "color": Fore.LIGHTGREEN_EX},
    {"id": 192, "name": "引力波稻穗", "cost": 2700, "growth_time": 1080, "yield_min": 3, "yield_max": 6, "value": 26000, "exp": 3400, "color": Fore.YELLOW},
    {"id": 193, "name": "机械齿轮花", "cost": 1500, "growth_time": 700, "yield_min": 2, "yield_max": 5, "value": 11000, "exp": 1800, "color": Fore.LIGHTWHITE_EX},
    {"id": 194, "name": "neon光纤草", "cost": 1700, "growth_time": 750, "yield_min": 3, "yield_max": 6, "value": 13000, "exp": 2000, "color": Fore.LIGHTBLUE_EX},
    {"id": 195, "name": "核辐射荧光豆", "cost": 1900, "growth_time": 820, "yield_min": 4, "yield_max": 8, "value": 15500, "exp": 2300, "color": Fore.LIGHTGREEN_EX},
    {"id": 196, "name": "赛博潘多拉", "cost": 3500, "growth_time": 1300, "yield_min": 1, "yield_max": 1, "value": 42000, "exp": 6000, "color": Fore.LIGHTRED_EX},
    {"id": 197, "name": "翡翠碧玉白菜", "cost": 4000, "growth_time": 1400, "yield_min": 1, "yield_max": 1, "value": 55000, "exp": 7500, "color": Fore.LIGHTGREEN_EX},
    {"id": 198, "name": "黄金摇钱树", "cost": 5000, "growth_time": 1500, "yield_min": 5, "yield_max": 15, "value": 88888, "exp": 9999, "color": Fore.LIGHTYELLOW_EX},
    {"id": 199, "name": "至尊氪金神草", "cost": 10000, "growth_time": 2000, "yield_min": 1, "yield_max": 1, "value": 200000, "exp": 20000, "color": Fore.LIGHTCYAN_EX},
    {"id": 200, "name": "千岁仙宠不老花", "cost": 50000, "growth_time": 5000, "yield_min": 1, "yield_max": 1, "value": 999999, "exp": 99999, "color": Fore.LIGHTMAGENTA_EX}
]

def get_plant_by_id(plant_id):
    """根据ID检索植物核心数据"""
    for p in PLANT_DATABASE:
        if p["id"] == plant_id: return p
    return None